apiVersion: v1
kind: Service
metadata:
  name: backend-hdlee
  labels:
    name: backend-hdlee
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-hdlee
  type: NodePort
